window.LOCAL_TRACKS = [
  {name:'小问题',artist:'AGA',url:'file:///Users/hujiyuan/Music/AGA - 小问题.flac',type:'file'},
  {name:'Closer To You (Live)',artist:'Adam Lambert',url:'file:///Users/hujiyuan/Music/Adam Lambert - Closer To You (Live).flac',type:'file'},
  {name:'Rolling in the Deep (Explicit)',artist:'Adele',url:'file:///Users/hujiyuan/Music/Adele - Rolling in the Deep (Explicit).flac',type:'file'},
  {name:'Someone Like You',artist:'Adele',url:'file:///Users/hujiyuan/Music/Adele - Someone Like You.flac',type:'file'},
  {name:'Sad Sometimes',artist:'Alan Walker _ CORSAK胡梦周 _ 黄霄雲',url:'file:///Users/hujiyuan/Music/Alan Walker _ CORSAK胡梦周 _ 黄霄雲 - Sad Sometimes.flac',type:'file'},
  {name:'Heartbeats',artist:'Amy Diamond',url:'file:///Users/hujiyuan/Music/Amy Diamond - Heartbeats.flac',type:'file'},
  {name:'A Thousand Years',artist:'Anthem Lights _ Megan Davies',url:'file:///Users/hujiyuan/Music/Anthem Lights _ Megan Davies - A Thousand Years.flac',type:'file'},
  {name:'Try',artist:'Asher Monroe',url:'file:///Users/hujiyuan/Music/Asher Monroe - Try.flac',type:'file'},
  {name:'半生你我',artist:'Assen捷',url:'file:///Users/hujiyuan/Music/Assen捷 - 半生你我.mp3',type:'file'},
  {name:'告白の夜 (告白之夜) (LIVE!! Ayasa Theater episode 7)hires',artist:'Ayasa绚沙',url:'file:///Users/hujiyuan/Music/Ayasa绚沙 - 告白の夜 (告白之夜) (LIVE!! Ayasa Theater episode 7)hires.flac',type:'file'},
  {name:'Flashback',artist:'Beatrich',url:'file:///Users/hujiyuan/Music/Beatrich - Flashback.flac',type:'file'},
  {name:'Halo',artist:'Beyoncé',url:'file:///Users/hujiyuan/Music/Beyoncé - Halo.flac',type:'file'},
  {name:'Six Feet Under',artist:'Billie Eilish',url:'file:///Users/hujiyuan/Music/Billie Eilish - Six Feet Under.flac',type:'file'},
  {name:'Dancing With a Stranger',artist:'Boyce Avenue _ Emma Heesters',url:'file:///Users/hujiyuan/Music/Boyce Avenue _ Emma Heesters - Dancing With a Stranger.flac',type:'file'},
  {name:'Wrap Me In Plastic',artist:'CHROMANCE',url:'file:///Users/hujiyuan/Music/CHROMANCE - Wrap Me In Plastic.flac',type:'file'},
  {name:'GLOW (feat_ Robinson)',artist:'CORSAK胡梦周 _ Robinson',url:'file:///Users/hujiyuan/Music/CORSAK胡梦周 _ Robinson - GLOW (feat_ Robinson).flac',type:'file'},
  {name:'轮回之境',artist:'CRITTY',url:'file:///Users/hujiyuan/Music/CRITTY - 轮回之境.flac',type:'file'},
  {name:'杏花弦外雨',artist:'CRITTY _ 司夏',url:'file:///Users/hujiyuan/Music/CRITTY _ 司夏 - 杏花弦外雨.flac',type:'file'},
  {name:'Sailing',artist:'Declan Galbraith',url:'file:///Users/hujiyuan/Music/Declan Galbraith - Sailing.flac',type:'file'},
  {name:'Tell Me Why (Radio Edit)',artist:'Declan Galbraith',url:'file:///Users/hujiyuan/Music/Declan Galbraith - Tell Me Why (Radio Edit).flac',type:'file'},
  {name:'Run Free (Original Mix)',artist:'Deep Chills _ IVIE',url:'file:///Users/hujiyuan/Music/Deep Chills _ IVIE - Run Free (Original Mix).flac',type:'file'},
  {name:'Dream It Possible',artist:'Delacey',url:'file:///Users/hujiyuan/Music/Delacey - Dream It Possible.flac',type:'file'},
  {name:'Last Goodbye',artist:'Denny White',url:'file:///Users/hujiyuan/Music/Denny White - Last Goodbye.mp3',type:'file'},
  {name:'Come Back For You',artist:'Elephante _ Matluck',url:'file:///Users/hujiyuan/Music/Elephante _ Matluck - Come Back For You.flac',type:'file'},
  {name:'My Sunset (Original Mix)',artist:'Feint',url:'file:///Users/hujiyuan/Music/Feint - My Sunset (Original Mix).flac',type:'file'},
  {name:'Lemon Tree',artist:'Fool\'s Garden',url:'file:///Users/hujiyuan/Music/Fool\'s Garden - Lemon Tree.flac',type:'file'},
  {name:'Remember Our Summer',artist:'FrogMonster',url:'file:///Users/hujiyuan/Music/FrogMonster - Remember Our Summer.flac',type:'file'},
  {name:'Me, Myself & I',artist:'G-Eazy _ Bebe Rexha',url:'file:///Users/hujiyuan/Music/G-Eazy _ Bebe Rexha - Me, Myself & I.flac',type:'file'},
  {name:'都市惊奇夜',artist:'GAI周延 _ 双笙 (陈元汐)',url:'file:///Users/hujiyuan/Music/GAI周延 _ 双笙 (陈元汐) - 都市惊奇夜.flac',type:'file'},
  {name:'No Fear (Explicit)',artist:'Greyson Chance',url:'file:///Users/hujiyuan/Music/Greyson Chance - No Fear (Explicit).flac',type:'file'},
  {name:'盗将行',artist:'HATO唱见组 _ 胖丁 _ 摸摸子',url:'file:///Users/hujiyuan/Music/HATO唱见组 _ 胖丁 _ 摸摸子 - 盗将行.mp3',type:'file'},
  {name:'云里江南',artist:'HITA',url:'file:///Users/hujiyuan/Music/HITA - 云里江南.mp3',type:'file'},
  {name:'Free to Be Me',artist:'Haroula Rose',url:'file:///Users/hujiyuan/Music/Haroula Rose - Free to Be Me.flac',type:'file'},
  {name:'风月令',artist:'IRiS七叶',url:'file:///Users/hujiyuan/Music/IRiS七叶 - 风月令.flac',type:'file'},
  {name:'Out Of Breath',artist:'Jared Lee',url:'file:///Users/hujiyuan/Music/Jared Lee - Out Of Breath.flac',type:'file'},
  {name:'Let It Go',artist:'Joshua Hyslop',url:'file:///Users/hujiyuan/Music/Joshua Hyslop - Let It Go.flac',type:'file'},
  {name:'Chasing The Wind',artist:'Josiah James',url:'file:///Users/hujiyuan/Music/Josiah James - Chasing The Wind.mp3',type:'file'},
  {name:'悦神 (纯歌版)',artist:'KBShinya',url:'file:///Users/hujiyuan/Music/KBShinya - 悦神 (纯歌版).flac',type:'file'},
  {name:'For the First Time in Forever',artist:'Kristen Bell _ Idina Menzel',url:'file:///Users/hujiyuan/Music/Kristen Bell _ Idina Menzel - For the First Time in Forever.flac',type:'file'},
  {name:'夏·烟火',artist:'LIKPIA',url:'file:///Users/hujiyuan/Music/LIKPIA - 夏·烟火.mp3',type:'file'},
  {name:'Need You Now',artist:'Lady A',url:'file:///Users/hujiyuan/Music/Lady A - Need You Now.flac',type:'file'},
  {name:'Blue Skies',artist:'Lenka',url:'file:///Users/hujiyuan/Music/Lenka - Blue Skies.flac',type:'file'},
  {name:'God Rest Ye Merry Gentlemen',artist:'Lindsey Stirling',url:'file:///Users/hujiyuan/Music/Lindsey Stirling - God Rest Ye Merry Gentlemen.flac',type:'file'},
  {name:'我的一个道姑朋友',artist:'Lon',url:'file:///Users/hujiyuan/Music/Lon - 我的一个道姑朋友.mp3',type:'file'},
  {name:'Proud Of You',artist:'M2M',url:'file:///Users/hujiyuan/Music/M2M - Proud Of You.mp3',type:'file'},
  {name:'Go Time',artist:'Mark Petrie',url:'file:///Users/hujiyuan/Music/Mark Petrie - Go Time.flac',type:'file'},
  {name:'Into You',artist:'Matisse & Sadko _ Hanne Mjøen',url:'file:///Users/hujiyuan/Music/Matisse & Sadko _ Hanne Mjøen - Into You.flac',type:'file'},
  {name:'Once upon a Time',artist:'Max Oazo _ Moonessa',url:'file:///Users/hujiyuan/Music/Max Oazo _ Moonessa - Once upon a Time.flac',type:'file'},
  {name:'Ordinary Day',artist:'Melanie Penn',url:'file:///Users/hujiyuan/Music/Melanie Penn - Ordinary Day.flac',type:'file'},
  {name:'Wild',artist:'Monogem',url:'file:///Users/hujiyuan/Music/Monogem - Wild.flac',type:'file'},
  {name:'万神纪 (古风抒情版)',artist:'Moonlight',url:'file:///Users/hujiyuan/Music/Moonlight - 万神纪 (古风抒情版).mp3',type:'file'},
  {name:'何以歌',artist:'Mukyo木西',url:'file:///Users/hujiyuan/Music/Mukyo木西 - 何以歌.mp3',type:'file'},
  {name:'不灭忠骨 (剧情版)',artist:'NL不分',url:'file:///Users/hujiyuan/Music/NL不分 - 不灭忠骨 (剧情版).mp3',type:'file'},
  {name:'离骚',artist:'NL不分 _ 徐远书 _ 奇然 _ 沈谧仁',url:'file:///Users/hujiyuan/Music/NL不分 _ 徐远书 _ 奇然 _ 沈谧仁 - 离骚.flac',type:'file'},
  {name:'Another Level',artist:'Oh The Larceny',url:'file:///Users/hujiyuan/Music/Oh The Larceny - Another Level.flac',type:'file'},
  {name:'Sunrise (Acoustic)',artist:'Our Last Night',url:'file:///Users/hujiyuan/Music/Our Last Night - Sunrise (Acoustic).flac',type:'file'},
  {name:'Mean',artist:'P!NK',url:'file:///Users/hujiyuan/Music/P!NK - Mean.flac',type:'file'},
  {name:'Romeo\'s Tune',artist:'Pajaro Sunrise',url:'file:///Users/hujiyuan/Music/Pajaro Sunrise - Romeo\'s Tune.flac',type:'file'},
  {name:'ILLENIUM _ Phoebe Ryan _ Martin Jensen - Mine Solo Dance(Pan_Sen_ Mashup)',artist:'Pan_Sen_',url:'file:///Users/hujiyuan/Music/Pan_Sen_ - ILLENIUM _ Phoebe Ryan _ Martin Jensen - Mine Solo Dance(Pan_Sen_ Mashup).mp3',type:'file'},
  {name:'Life Goes On (Remix)',artist:'ROSE BEAT',url:'file:///Users/hujiyuan/Music/ROSE BEAT - Life Goes On (Remix).flac',type:'file'},
  {name:'Bamboo',artist:'Raujika',url:'file:///Users/hujiyuan/Music/Raujika - Bamboo.mp3',type:'file'},
  {name:'Kai\'s Theme',artist:'Samuel Kim',url:'file:///Users/hujiyuan/Music/Samuel Kim - Kai\'s Theme.flac',type:'file'},
  {name:'Reminding Me',artist:'Shawn Hook _ Vanessa Hudgens',url:'file:///Users/hujiyuan/Music/Shawn Hook _ Vanessa Hudgens - Reminding Me.flac',type:'file'},
  {name:'Until You',artist:'Shayne Ward',url:'file:///Users/hujiyuan/Music/Shayne Ward - Until You.flac',type:'file'},
  {name:'皆斩--剑网情缘叁·恶人谷',artist:'Smile_小千',url:'file:///Users/hujiyuan/Music/Smile_小千 - 皆斩--剑网情缘叁·恶人谷.flac',type:'file'},
  {name:'Sakura Tears',artist:'Snigellin',url:'file:///Users/hujiyuan/Music/Snigellin - Sakura Tears.flac',type:'file'},
  {name:'Valder Fields',artist:'Tamas Wells',url:'file:///Users/hujiyuan/Music/Tamas Wells - Valder Fields.flac',type:'file'},
  {name:'Safe & Sound (from The Hunger Games Soundtrack)',artist:'Taylor Swift _ The Civil Wars',url:'file:///Users/hujiyuan/Music/Taylor Swift _ The Civil Wars - Safe & Sound (from The Hunger Games Soundtrack).flac',type:'file'},
  {name:'RISE',artist:'The Glitch Mob _ Mako _ The Word Alive',url:'file:///Users/hujiyuan/Music/The Glitch Mob _ Mako _ The Word Alive - RISE.flac',type:'file'},
  {name:'Rise Up',artist:'TheFatRat',url:'file:///Users/hujiyuan/Music/TheFatRat - Rise Up.flac',type:'file'},
  {name:'We\'ll Meet Again',artist:'TheFatRat _ Laura Brehm',url:'file:///Users/hujiyuan/Music/TheFatRat _ Laura Brehm - We\'ll Meet Again.flac',type:'file'},
  {name:'Watch Me Work',artist:'Tinashe',url:'file:///Users/hujiyuan/Music/Tinashe - Watch Me Work.flac',type:'file'},
  {name:'杀破狼',artist:'Vitas',url:'file:///Users/hujiyuan/Music/Vitas - 杀破狼.flac',type:'file'},
  {name:'何曾惧',artist:'Vk _ 五音Jw _ Aki阿杰',url:'file:///Users/hujiyuan/Music/Vk _ 五音Jw _ Aki阿杰 - 何曾惧.flac',type:'file'},
  {name:'忘尘如羡 (Assen捷_老虎欧巴)',artist:'W_K_ _ 易羲',url:'file:///Users/hujiyuan/Music/W_K_ _ 易羲 - 忘尘如羡 (Assen捷_老虎欧巴).mp3',type:'file'},
  {name:'My Blood',artist:'Westlife',url:'file:///Users/hujiyuan/Music/Westlife - My Blood.flac',type:'file'},
  {name:'My Love',artist:'Westlife',url:'file:///Users/hujiyuan/Music/Westlife - My Love.flac',type:'file'},
  {name:'菁华浮梦',artist:'Winky诗[赵景旭]',url:'file:///Users/hujiyuan/Music/Winky诗[赵景旭] - 菁华浮梦.mp3',type:'file'},
  {name:'summertime (夏日时光)',artist:'cinnamons _ evening cinema',url:'file:///Users/hujiyuan/Music/cinnamons _ evening cinema - summertime (夏日时光).flac',type:'file'},
  {name:'将军令',artist:'cv王胖子 _ 西瓜JUN',url:'file:///Users/hujiyuan/Music/cv王胖子 _ 西瓜JUN - 将军令.mp3',type:'file'},
  {name:'鱼玄机',artist:'hanser',url:'file:///Users/hujiyuan/Music/hanser - 鱼玄机.mp3',type:'file'},
  {name:'梦雨潇潇',artist:'shelly佳',url:'file:///Users/hujiyuan/Music/shelly佳 - 梦雨潇潇.flac',type:'file'},
  {name:'盛世繁华',artist:'shelly佳',url:'file:///Users/hujiyuan/Music/shelly佳 - 盛世繁华.flac',type:'file'},
  {name:'雾醉念',artist:'shelly佳',url:'file:///Users/hujiyuan/Music/shelly佳 - 雾醉念.flac',type:'file'},
  {name:'路之遥',artist:'丁丁',url:'file:///Users/hujiyuan/Music/丁丁 - 路之遥.flac',type:'file'},
  {name:'城南花已开',artist:'三亩地',url:'file:///Users/hujiyuan/Music/三亩地 - 城南花已开.flac',type:'file'},
  {name:'十二镇魂歌',artist:'三无Marblue',url:'file:///Users/hujiyuan/Music/三无Marblue - 十二镇魂歌.mp3',type:'file'},
  {name:'桃花劫',artist:'东篱',url:'file:///Users/hujiyuan/Music/东篱 - 桃花劫.mp3',type:'file'},
  {name:'咏心',artist:'东篱 _ Assen捷',url:'file:///Users/hujiyuan/Music/东篱 _ Assen捷 - 咏心.mp3',type:'file'},
  {name:'与天为敌',artist:'严艺丹',url:'file:///Users/hujiyuan/Music/严艺丹 - 与天为敌.flac',type:'file'},
  {name:'有人',artist:'丫蛋蛋换个心情做自己',url:'file:///Users/hujiyuan/Music/丫蛋蛋换个心情做自己 - 有人.mp3',type:'file'},
  {name:'痴狂',artist:'丫蛋蛋（马启涵）',url:'file:///Users/hujiyuan/Music/丫蛋蛋（马启涵） - 痴狂.flac',type:'file'},
  {name:'起风了hires',artist:'买辣椒也用券',url:'file:///Users/hujiyuan/Music/买辣椒也用券 - 起风了hires.flac',type:'file'},
  {name:'不负时光 (Live)',artist:'云之泣 _ 张一末（灰老板） _ 蔡明希-不才',url:'file:///Users/hujiyuan/Music/云之泣 _ 张一末（灰老板） _ 蔡明希-不才 - 不负时光 (Live).mp3',type:'file'},
  {name:'催雪忘故',artist:'伦桑',url:'file:///Users/hujiyuan/Music/伦桑 - 催雪忘故.flac',type:'file'},
  {name:'龙武盛唐(1)',artist:'伦桑',url:'file:///Users/hujiyuan/Music/伦桑 - 龙武盛唐(1).flac',type:'file'},
  {name:'龙武盛唐',artist:'伦桑',url:'file:///Users/hujiyuan/Music/伦桑 - 龙武盛唐.flac',type:'file'},
  {name:'无期',artist:'光头华夏',url:'file:///Users/hujiyuan/Music/光头华夏 - 无期.flac',type:'file'},
  {name:'一念众生',artist:'冬子',url:'file:///Users/hujiyuan/Music/冬子 - 一念众生.flac',type:'file'},
  {name:'一剑留名',artist:'十二律音乐联盟',url:'file:///Users/hujiyuan/Music/十二律音乐联盟 - 一剑留名.flac',type:'file'},
  {name:'丰碑',artist:'十二律音乐联盟',url:'file:///Users/hujiyuan/Music/十二律音乐联盟 - 丰碑.mp3',type:'file'},
  {name:'剑行江湖',artist:'十二律音乐联盟',url:'file:///Users/hujiyuan/Music/十二律音乐联盟 - 剑行江湖.flac',type:'file'},
  {name:'Starry',artist:'千坂',url:'file:///Users/hujiyuan/Music/千坂 - Starry.flac',type:'file'},
  {name:'Here We Are',artist:'华晨宇',url:'file:///Users/hujiyuan/Music/华晨宇 - Here We Are.flac',type:'file'},
  {name:'烟火里的尘埃 (Live)',artist:'华晨宇',url:'file:///Users/hujiyuan/Music/华晨宇 - 烟火里的尘埃 (Live).mp3',type:'file'},
  {name:'天下潮·雪中悍刀行群像 (剧情版)',artist:'华语群星',url:'file:///Users/hujiyuan/Music/华语群星 - 天下潮·雪中悍刀行群像 (剧情版).mp3',type:'file'},
  {name:'天下潮·雪中悍刀行群像',artist:'华语群星',url:'file:///Users/hujiyuan/Music/华语群星 - 天下潮·雪中悍刀行群像.mp3',type:'file'},
  {name:'梦回九龙朝',artist:'华语群星',url:'file:///Users/hujiyuan/Music/华语群星 - 梦回九龙朝.mp3',type:'file'},
  {name:'在夜里跳舞',artist:'单依纯',url:'file:///Users/hujiyuan/Music/单依纯 - 在夜里跳舞.flac',type:'file'},
  {name:'我在城外等着你',artist:'单色凌',url:'file:///Users/hujiyuan/Music/单色凌 - 我在城外等着你.flac',type:'file'},
  {name:'乱尘戏',artist:'南以鸣 _ 晏鸩',url:'file:///Users/hujiyuan/Music/南以鸣 _ 晏鸩 - 乱尘戏.mp3',type:'file'},
  {name:'花满庭',artist:'叁汀 _ 秋仁',url:'file:///Users/hujiyuan/Music/叁汀 _ 秋仁 - 花满庭.flac',type:'file'},
  {name:'寻·梦归',artist:'双笙 (陈元汐)',url:'file:///Users/hujiyuan/Music/双笙 (陈元汐) - 寻·梦归.flac',type:'file'},
  {name:'独步尘寰',artist:'双笙 (陈元汐)',url:'file:///Users/hujiyuan/Music/双笙 (陈元汐) - 独步尘寰.mp3',type:'file'},
  {name:'锦鲤抄',artist:'双笙 (陈元汐)',url:'file:///Users/hujiyuan/Music/双笙 (陈元汐) - 锦鲤抄.mp3',type:'file'},
  {name:'问剑江湖',artist:'双笙 (陈元汐)',url:'file:///Users/hujiyuan/Music/双笙 (陈元汐) - 问剑江湖.flac',type:'file'},
  {name:'阴阳诀',artist:'双笙 (陈元汐)',url:'file:///Users/hujiyuan/Music/双笙 (陈元汐) - 阴阳诀.flac',type:'file'},
  {name:'马步谣',artist:'双笙 (陈元汐)',url:'file:///Users/hujiyuan/Music/双笙 (陈元汐) - 马步谣.flac',type:'file'},
  {name:'岁月旧曾谙',artist:'双笙 (陈元汐) _ 三无',url:'file:///Users/hujiyuan/Music/双笙 (陈元汐) _ 三无 - 岁月旧曾谙.mp3',type:'file'},
  {name:'岁月旧曾谙',artist:'双笙 (陈元汐) _ 三无Marblue',url:'file:///Users/hujiyuan/Music/双笙 (陈元汐) _ 三无Marblue - 岁月旧曾谙.mp3',type:'file'},
  {name:'白石溪',artist:'双笙 (陈元汐) _ 冥月',url:'file:///Users/hujiyuan/Music/双笙 (陈元汐) _ 冥月 - 白石溪.mp3',type:'file'},
  {name:'天地茫茫',artist:'古剑奇谭',url:'file:///Users/hujiyuan/Music/古剑奇谭 - 天地茫茫.mp3',type:'file'},
  {name:'蜉蝣梦',artist:'叶洛洛',url:'file:///Users/hujiyuan/Music/叶洛洛 - 蜉蝣梦.mp3',type:'file'},
  {name:'忆江南',artist:'叶洛洛 _ 西瓜JUN',url:'file:///Users/hujiyuan/Music/叶洛洛 _ 西瓜JUN - 忆江南.mp3',type:'file'},
  {name:'无归',artist:'叶里',url:'file:///Users/hujiyuan/Music/叶里 - 无归.mp3',type:'file'},
  {name:'烟花易冷',artist:'周杰伦',url:'file:///Users/hujiyuan/Music/周杰伦 - 烟花易冷.flac',type:'file'},
  {name:'红尘客栈',artist:'周杰伦',url:'file:///Users/hujiyuan/Music/周杰伦 - 红尘客栈.flac',type:'file'},
  {name:'霍元甲',artist:'周杰伦',url:'file:///Users/hujiyuan/Music/周杰伦 - 霍元甲.flac',type:'file'},
  {name:'人间不值得',artist:'大柯',url:'file:///Users/hujiyuan/Music/大柯 - 人间不值得.flac',type:'file'},
  {name:'琵琶行',artist:'奇然 _ 沈谧仁',url:'file:///Users/hujiyuan/Music/奇然 _ 沈谧仁 - 琵琶行.flac',type:'file'},
  {name:'阿房宫赋 (Demo)',artist:'奇然 _ 沈谧仁',url:'file:///Users/hujiyuan/Music/奇然 _ 沈谧仁 - 阿房宫赋 (Demo).flac',type:'file'},
  {name:'千金埋骨',artist:'奇然 _ 重小烟',url:'file:///Users/hujiyuan/Music/奇然 _ 重小烟 - 千金埋骨.mp3',type:'file'},
  {name:'御龙吟',artist:'姚贝娜',url:'file:///Users/hujiyuan/Music/姚贝娜 - 御龙吟.flac',type:'file'},
  {name:'可不可以 (女声版)',artist:'季彦霖',url:'file:///Users/hujiyuan/Music/季彦霖 - 可不可以 (女声版).flac',type:'file'},
  {name:'朱雀街',artist:'宋秉洋',url:'file:///Users/hujiyuan/Music/宋秉洋 - 朱雀街.flac',type:'file'},
  {name:'一百',artist:'宝石Gem',url:'file:///Users/hujiyuan/Music/宝石Gem - 一百.flac',type:'file'},
  {name:'不羡明月知',artist:'封茗囧菌',url:'file:///Users/hujiyuan/Music/封茗囧菌 - 不羡明月知.mp3',type:'file'},
  {name:'千帆尽 (人声本家)',artist:'封茗囧菌',url:'file:///Users/hujiyuan/Music/封茗囧菌 - 千帆尽 (人声本家).mp3',type:'file'},
  {name:'危年不祈',artist:'封茗囧菌',url:'file:///Users/hujiyuan/Music/封茗囧菌 - 危年不祈.mp3',type:'file'},
  {name:'旧雨',artist:'封茗囧菌',url:'file:///Users/hujiyuan/Music/封茗囧菌 - 旧雨.mp3',type:'file'},
  {name:'王妃',artist:'封茗囧菌',url:'file:///Users/hujiyuan/Music/封茗囧菌 - 王妃.mp3',type:'file'},
  {name:'轮回之境',artist:'封茗囧菌',url:'file:///Users/hujiyuan/Music/封茗囧菌 - 轮回之境.mp3',type:'file'},
  {name:'风华燃尽',artist:'封茗囧菌',url:'file:///Users/hujiyuan/Music/封茗囧菌 - 风华燃尽.mp3',type:'file'},
  {name:'世末歌者',artist:'封茗囧菌 _ 双笙 (陈元汐)',url:'file:///Users/hujiyuan/Music/封茗囧菌 _ 双笙 (陈元汐) - 世末歌者.mp3',type:'file'},
  {name:'霜雪千年',artist:'封茗囧菌 _ 双笙 (陈元汐)',url:'file:///Users/hujiyuan/Music/封茗囧菌 _ 双笙 (陈元汐) - 霜雪千年.mp3',type:'file'},
  {name:'西狂',artist:'小旭音乐',url:'file:///Users/hujiyuan/Music/小旭音乐 - 西狂.mp3',type:'file'},
  {name:'就是你',artist:'小旭音乐 _ 王玥',url:'file:///Users/hujiyuan/Music/小旭音乐 _ 王玥 - 就是你.flac',type:'file'},
  {name:'浮云生死',artist:'小曲儿 _ 张承煜（小魂）',url:'file:///Users/hujiyuan/Music/小曲儿 _ 张承煜（小魂） - 浮云生死.mp3',type:'file'},
  {name:'学猫叫',artist:'小潘潘（潘柚彤） _ 小峰峰（陈峰）',url:'file:///Users/hujiyuan/Music/小潘潘（潘柚彤） _ 小峰峰（陈峰） - 学猫叫.flac',type:'file'},
  {name:'宠坏 (可不可以你把我宠坏)',artist:'小潘潘（潘柚彤） _ 李俊佑',url:'file:///Users/hujiyuan/Music/小潘潘（潘柚彤） _ 李俊佑 - 宠坏 (可不可以你把我宠坏).flac',type:'file'},
  {name:'在下，沈剑心！',artist:'小爱的妈 _ 雨洛Huge',url:'file:///Users/hujiyuan/Music/小爱的妈 _ 雨洛Huge - 在下，沈剑心！.mp3',type:'file'},
  {name:'镇魂',artist:'小田音乐社 _ 灼夭',url:'file:///Users/hujiyuan/Music/小田音乐社 _ 灼夭 - 镇魂.flac',type:'file'},
  {name:'以劍之名—血薇',artist:'少司命',url:'file:///Users/hujiyuan/Music/少司命 - 以劍之名—血薇.mp3',type:'file'},
  {name:'闲岁',artist:'少年霜 _ CRITTY',url:'file:///Users/hujiyuan/Music/少年霜 _ CRITTY - 闲岁.mp3',type:'file'},
  {name:'灯火里的中国 (舒楠监制 官方正式版)',artist:'张也 _ 周深',url:'file:///Users/hujiyuan/Music/张也 _ 周深 - 灯火里的中国 (舒楠监制 官方正式版).flac',type:'file'},
  {name:'凡生',artist:'张承煜（小魂）',url:'file:///Users/hujiyuan/Music/张承煜（小魂） - 凡生.mp3',type:'file'},
  {name:'溪语',artist:'张承煜（小魂）',url:'file:///Users/hujiyuan/Music/张承煜（小魂） - 溪语.mp3',type:'file'},
  {name:'烟云晚枫',artist:'张承煜（小魂）',url:'file:///Users/hujiyuan/Music/张承煜（小魂） - 烟云晚枫.flac',type:'file'},
  {name:'焚海',artist:'张承煜（小魂）',url:'file:///Users/hujiyuan/Music/张承煜（小魂） - 焚海.mp3',type:'file'},
  {name:'花满楼',artist:'张承煜（小魂）',url:'file:///Users/hujiyuan/Music/张承煜（小魂） - 花满楼.flac',type:'file'},
  {name:'Layla蕾拉',artist:'张杰',url:'file:///Users/hujiyuan/Music/张杰 - Layla蕾拉.flac',type:'file'},
  {name:'天下 (Live)',artist:'张杰',url:'file:///Users/hujiyuan/Music/张杰 - 天下 (Live).flac',type:'file'},
  {name:'浮诛',artist:'张杰',url:'file:///Users/hujiyuan/Music/张杰 - 浮诛.flac',type:'file'},
  {name:'一个人',artist:'张艺兴',url:'file:///Users/hujiyuan/Music/张艺兴 - 一个人.flac',type:'file'},
  {name:'就算',artist:'张靓颖',url:'file:///Users/hujiyuan/Music/张靓颖 - 就算.flac',type:'file'},
  {name:'天下',artist:'徐嘉苇',url:'file:///Users/hujiyuan/Music/徐嘉苇 - 天下.flac',type:'file'},
  {name:'御龙品青梅',artist:'御龙在天 _ 刘惜君',url:'file:///Users/hujiyuan/Music/御龙在天 _ 刘惜君 - 御龙品青梅.flac',type:'file'},
  {name:'御龙耀九天',artist:'御龙在天 _ 周笔畅',url:'file:///Users/hujiyuan/Music/御龙在天 _ 周笔畅 - 御龙耀九天.mp3',type:'file'},
  {name:'御龙铭千古',artist:'御龙在天 _ 林志炫',url:'file:///Users/hujiyuan/Music/御龙在天 _ 林志炫 - 御龙铭千古.flac',type:'file'},
  {name:'盛世回首',artist:'慕寒 _ 马里奥',url:'file:///Users/hujiyuan/Music/慕寒 _ 马里奥 - 盛世回首.mp3',type:'file'},
  {name:'缠心莲',artist:'慕斯の小乖',url:'file:///Users/hujiyuan/Music/慕斯の小乖 - 缠心莲.mp3',type:'file'},
  {name:'东风第一枝',artist:'执素兮',url:'file:///Users/hujiyuan/Music/执素兮 - 东风第一枝.mp3',type:'file'},
  {name:'一眼旧梦',artist:'排骨教主',url:'file:///Users/hujiyuan/Music/排骨教主 - 一眼旧梦.flac',type:'file'},
  {name:'伶人',artist:'排骨教主',url:'file:///Users/hujiyuan/Music/排骨教主 - 伶人.flac',type:'file'},
  {name:'别有天',artist:'排骨教主',url:'file:///Users/hujiyuan/Music/排骨教主 - 别有天.flac',type:'file'},
  {name:'剑之道',artist:'排骨教主',url:'file:///Users/hujiyuan/Music/排骨教主 - 剑之道.mp3',type:'file'},
  {name:'十二镇魂歌',artist:'排骨教主',url:'file:///Users/hujiyuan/Music/排骨教主 - 十二镇魂歌.mp3',type:'file'},
  {name:'君临天下',artist:'排骨教主',url:'file:///Users/hujiyuan/Music/排骨教主 - 君临天下.mp3',type:'file'},
  {name:'天涯',artist:'排骨教主',url:'file:///Users/hujiyuan/Music/排骨教主 - 天涯.mp3',type:'file'},
  {name:'战',artist:'排骨教主',url:'file:///Users/hujiyuan/Music/排骨教主 - 战.mp3',type:'file'},
  {name:'明月本无心',artist:'排骨教主',url:'file:///Users/hujiyuan/Music/排骨教主 - 明月本无心.flac',type:'file'},
  {name:'狂野想乡',artist:'排骨教主',url:'file:///Users/hujiyuan/Music/排骨教主 - 狂野想乡.mp3',type:'file'},
  {name:'白石溪',artist:'排骨教主',url:'file:///Users/hujiyuan/Music/排骨教主 - 白石溪.mp3',type:'file'},
  {name:'红妆',artist:'排骨教主',url:'file:///Users/hujiyuan/Music/排骨教主 - 红妆.mp3',type:'file'},
  {name:'红颜旧',artist:'排骨教主',url:'file:///Users/hujiyuan/Music/排骨教主 - 红颜旧.mp3',type:'file'},
  {name:'长生诀',artist:'排骨教主',url:'file:///Users/hujiyuan/Music/排骨教主 - 长生诀.mp3',type:'file'},
  {name:'霜雪千年',artist:'排骨教主',url:'file:///Users/hujiyuan/Music/排骨教主 - 霜雪千年.mp3',type:'file'},
  {name:'故人叹',artist:'排骨教主 _ cv王胖子 _ 西瓜JUN',url:'file:///Users/hujiyuan/Music/排骨教主 _ cv王胖子 _ 西瓜JUN - 故人叹.mp3',type:'file'},
  {name:'芊芊',artist:'排骨教主 _ 西瓜JUN',url:'file:///Users/hujiyuan/Music/排骨教主 _ 西瓜JUN - 芊芊.mp3',type:'file'},
  {name:'锦鲤抄',artist:'排骨教主 _ 西瓜JUN',url:'file:///Users/hujiyuan/Music/排骨教主 _ 西瓜JUN - 锦鲤抄.mp3',type:'file'},
  {name:'狐言',artist:'排骨教主 _ 银临',url:'file:///Users/hujiyuan/Music/排骨教主 _ 银临 - 狐言.mp3',type:'file'},
  {name:'想象 (Live)',artist:'摩登兄弟',url:'file:///Users/hujiyuan/Music/摩登兄弟 - 想象 (Live).flac',type:'file'},
  {name:'想象',artist:'摩登兄弟刘宇宁',url:'file:///Users/hujiyuan/Music/摩登兄弟刘宇宁 - 想象.flac',type:'file'},
  {name:'剑鞘',artist:'文儿',url:'file:///Users/hujiyuan/Music/文儿 - 剑鞘.mp3',type:'file'},
  {name:'Die For You (为你而战)',artist:'无畏契约 _ Grabbitz',url:'file:///Users/hujiyuan/Music/无畏契约 _ Grabbitz - Die For You (为你而战).flac',type:'file'},
  {name:'封刀不为峥嵘',artist:'易世樊花',url:'file:///Users/hujiyuan/Music/易世樊花 - 封刀不为峥嵘.flac',type:'file'},
  {name:'明月天涯',artist:'易言 _ 三无Marblue',url:'file:///Users/hujiyuan/Music/易言 _ 三无Marblue - 明月天涯.mp3',type:'file'},
  {name:'万神纪',artist:'易言 _ 樊棋 _ 三无Marblue _ 双笙 (陈元汐)',url:'file:///Users/hujiyuan/Music/易言 _ 樊棋 _ 三无Marblue _ 双笙 (陈元汐) - 万神纪.mp3',type:'file'},
  {name:'修炼爱情',artist:'昼夜',url:'file:///Users/hujiyuan/Music/昼夜 - 修炼爱情.mp3',type:'file'},
  {name:'六月的雨',artist:'昼夜',url:'file:///Users/hujiyuan/Music/昼夜 - 六月的雨.mp3',type:'file'},
  {name:'剑心',artist:'昼夜',url:'file:///Users/hujiyuan/Music/昼夜 - 剑心.mp3',type:'file'},
  {name:'夏天的风 (钢琴版)',artist:'昼夜',url:'file:///Users/hujiyuan/Music/昼夜 - 夏天的风 (钢琴版).mp3',type:'file'},
  {name:'天空之城',artist:'昼夜',url:'file:///Users/hujiyuan/Music/昼夜 - 天空之城.flac',type:'file'},
  {name:'山外小楼夜听雨',artist:'昼夜',url:'file:///Users/hujiyuan/Music/昼夜 - 山外小楼夜听雨.mp3',type:'file'},
  {name:'承剑',artist:'昼夜',url:'file:///Users/hujiyuan/Music/昼夜 - 承剑.mp3',type:'file'},
  {name:'折子戏',artist:'昼夜',url:'file:///Users/hujiyuan/Music/昼夜 - 折子戏.mp3',type:'file'},
  {name:'枫',artist:'昼夜',url:'file:///Users/hujiyuan/Music/昼夜 - 枫.mp3',type:'file'},
  {name:'狐言 钢琴版',artist:'昼夜',url:'file:///Users/hujiyuan/Music/昼夜 - 狐言 钢琴版.mp3',type:'file'},
  {name:'荣耀',artist:'昼夜',url:'file:///Users/hujiyuan/Music/昼夜 - 荣耀.mp3',type:'file'},
  {name:'醉赤壁',artist:'昼夜',url:'file:///Users/hujiyuan/Music/昼夜 - 醉赤壁.mp3',type:'file'},
  {name:'长生诀',artist:'昼夜',url:'file:///Users/hujiyuan/Music/昼夜 - 长生诀.mp3',type:'file'},
  {name:'棠花谢',artist:'晃儿 _ 慕寒',url:'file:///Users/hujiyuan/Music/晃儿 _ 慕寒 - 棠花谢.mp3',type:'file'},
  {name:'九张机',artist:'曼曼的钢琴城堡',url:'file:///Users/hujiyuan/Music/曼曼的钢琴城堡 - 九张机.mp3',type:'file'},
  {name:'以身戮恶',artist:'朱强 _ 吾恩 _ Assen捷 _ T-Tone',url:'file:///Users/hujiyuan/Music/朱强 _ 吾恩 _ Assen捷 _ T-Tone - 以身戮恶.mp3',type:'file'},
  {name:'蜀绣 (春晚版)',artist:'李宇春',url:'file:///Users/hujiyuan/Music/李宇春 - 蜀绣 (春晚版).flac',type:'file'},
  {name:'我是真的爱你',artist:'李宗盛',url:'file:///Users/hujiyuan/Music/李宗盛 - 我是真的爱你.flac',type:'file'},
  {name:'与妆',artist:'李常超（Lao乾妈）',url:'file:///Users/hujiyuan/Music/李常超（Lao乾妈） - 与妆.mp3',type:'file'},
  {name:'盗墓笔记·十年人间',artist:'李常超（Lao乾妈）',url:'file:///Users/hujiyuan/Music/李常超（Lao乾妈） - 盗墓笔记·十年人间.flac',type:'file'},
  {name:'剑伤',artist:'李易峰',url:'file:///Users/hujiyuan/Music/李易峰 - 剑伤.flac',type:'file'},
  {name:'国色天香 (Live)',artist:'李玉刚 _ 霍尊',url:'file:///Users/hujiyuan/Music/李玉刚 _ 霍尊 - 国色天香 (Live).mp3',type:'file'},
  {name:'笨小孩 (Live)',artist:'杨宗纬 _ 李晨 _ 华晨宇',url:'file:///Users/hujiyuan/Music/杨宗纬 _ 李晨 _ 华晨宇 - 笨小孩 (Live).flac',type:'file'},
  {name:'樱花草 (Single Version)',artist:'林依婷',url:'file:///Users/hujiyuan/Music/林依婷 - 樱花草 (Single Version).mp3',type:'file'},
  {name:'全世界谁倾听你',artist:'林宥嘉',url:'file:///Users/hujiyuan/Music/林宥嘉 - 全世界谁倾听你.flac',type:'file'},
  {name:'烟花易冷 (Live)',artist:'林志炫',url:'file:///Users/hujiyuan/Music/林志炫 - 烟花易冷 (Live).flac',type:'file'},
  {name:'慕情芳魂曲',artist:'林清弄',url:'file:///Users/hujiyuan/Music/林清弄 - 慕情芳魂曲.mp3',type:'file'},
  {name:'[群星]【残酷的高考纲领】',artist:'模仿翻唱',url:'file:///Users/hujiyuan/Music/模仿翻唱 - [群星]【残酷的高考纲领】.mp3',type:'file'},
  {name:'古城一侧',artist:'毛儿 _ 纸无笔砚',url:'file:///Users/hujiyuan/Music/毛儿 _ 纸无笔砚 - 古城一侧.flac',type:'file'},
  {name:'江南夜色',artist:'沈雨萱',url:'file:///Users/hujiyuan/Music/沈雨萱 - 江南夜色.mp3',type:'file'},
  {name:'依山观澜',artist:'河图',url:'file:///Users/hujiyuan/Music/河图 - 依山观澜.mp3',type:'file'},
  {name:'倾尽天下',artist:'河图',url:'file:///Users/hujiyuan/Music/河图 - 倾尽天下.flac',type:'file'},
  {name:'守',artist:'河图',url:'file:///Users/hujiyuan/Music/河图 - 守.flac',type:'file'},
  {name:'掺香',artist:'河图',url:'file:///Users/hujiyuan/Music/河图 - 掺香.flac',type:'file'},
  {name:'第三十八年夏至',artist:'河图',url:'file:///Users/hujiyuan/Music/河图 - 第三十八年夏至.flac',type:'file'},
  {name:'风起天阑',artist:'河图',url:'file:///Users/hujiyuan/Music/河图 - 风起天阑.flac',type:'file'},
  {name:'南柯梦',artist:'泥鳅Niko',url:'file:///Users/hujiyuan/Music/泥鳅Niko - 南柯梦.mp3',type:'file'},
  {name:'长风相知少年意',artist:'泥鳅Niko',url:'file:///Users/hujiyuan/Music/泥鳅Niko - 长风相知少年意.mp3',type:'file'},
  {name:'一梦千朝',artist:'洛天依',url:'file:///Users/hujiyuan/Music/洛天依 - 一梦千朝.mp3',type:'file'},
  {name:'蜀绣',artist:'海佳',url:'file:///Users/hujiyuan/Music/海佳 - 蜀绣.mp3',type:'file'},
  {name:'落花情',artist:'满汉全席',url:'file:///Users/hujiyuan/Music/满汉全席 - 落花情.mp3',type:'file'},
  {name:'剑濯山河',artist:'無名原创音乐团队',url:'file:///Users/hujiyuan/Music/無名原创音乐团队 - 剑濯山河.flac',type:'file'},
  {name:'戏语花',artist:'玄觞',url:'file:///Users/hujiyuan/Music/玄觞 - 戏语花.mp3',type:'file'},
  {name:'黯然销魂(1)',artist:'玄觞',url:'file:///Users/hujiyuan/Music/玄觞 - 黯然销魂(1).flac',type:'file'},
  {name:'黯然销魂',artist:'玄觞',url:'file:///Users/hujiyuan/Music/玄觞 - 黯然销魂.flac',type:'file'},
  {name:'风华诀',artist:'玄觞 _ 二花',url:'file:///Users/hujiyuan/Music/玄觞 _ 二花 - 风华诀.mp3',type:'file'},
  {name:'断戟的约定 (悲壮版)',artist:'王小小 _ 朴爱源 _ 王者荣耀',url:'file:///Users/hujiyuan/Music/王小小 _ 朴爱源 _ 王者荣耀 - 断戟的约定 (悲壮版).flac',type:'file'},
  {name:'断戟的约定 (柔情版)',artist:'王小小 _ 朴爱源 _ 王者荣耀',url:'file:///Users/hujiyuan/Music/王小小 _ 朴爱源 _ 王者荣耀 - 断戟的约定 (柔情版).flac',type:'file'},
  {name:'荣耀',artist:'王晓天',url:'file:///Users/hujiyuan/Music/王晓天 - 荣耀.flac',type:'file'},
  {name:'Evolve (淬炼)',artist:'王者荣耀 _ Ki_Theory',url:'file:///Users/hujiyuan/Music/王者荣耀 _ Ki_Theory - Evolve (淬炼).flac',type:'file'},
  {name:'百战成诗 (现场版_2020王者共创·荣耀盛典102古风唱将献礼)',artist:'王者荣耀同人局',url:'file:///Users/hujiyuan/Music/王者荣耀同人局 - 百战成诗 (现场版_2020王者共创·荣耀盛典102古风唱将献礼).flac',type:'file'},
  {name:'百战成诗',artist:'王者荣耀同人局',url:'file:///Users/hujiyuan/Music/王者荣耀同人局 - 百战成诗.flac',type:'file'},
  {name:'半生你我',artist:'琉森',url:'file:///Users/hujiyuan/Music/琉森 - 半生你我.mp3',type:'file'},
  {name:'弱水三千',artist:'石头 _ 张晓棠',url:'file:///Users/hujiyuan/Music/石头 _ 张晓棠 - 弱水三千.flac',type:'file'},
  {name:'Glimmer',artist:'祈Inory',url:'file:///Users/hujiyuan/Music/祈Inory - Glimmer.mp3',type:'file'},
  {name:'十二美人图',artist:'秦岚',url:'file:///Users/hujiyuan/Music/秦岚 - 十二美人图.flac',type:'file'},
  {name:'三生缘 (Live)',artist:'程响',url:'file:///Users/hujiyuan/Music/程响 - 三生缘 (Live).mp3',type:'file'},
  {name:'东风志 (竹笛钢琴合奏版)',artist:'笛呆子囚牛 _ 昼夜',url:'file:///Users/hujiyuan/Music/笛呆子囚牛 _ 昼夜 - 东风志 (竹笛钢琴合奏版).mp3',type:'file'},
  {name:'东流',artist:'绯村柯北 _ 张一末（灰老板）',url:'file:///Users/hujiyuan/Music/绯村柯北 _ 张一末（灰老板） - 东流.flac',type:'file'},
  {name:'出山',artist:'绯颜梨梦',url:'file:///Users/hujiyuan/Music/绯颜梨梦 - 出山.flac',type:'file'},
  {name:'北凉歌',artist:'网络歌手',url:'file:///Users/hujiyuan/Music/网络歌手 - 北凉歌.mp3',type:'file'},
  {name:'青春之火',artist:'罗玮洛',url:'file:///Users/hujiyuan/Music/罗玮洛 - 青春之火.mp3',type:'file'},
  {name:'万神纪',artist:'肥皂菌丨珉珉的猫咪丨',url:'file:///Users/hujiyuan/Music/肥皂菌丨珉珉的猫咪丨 - 万神纪.flac',type:'file'},
  {name:'刀塔传奇',artist:'胡夏',url:'file:///Users/hujiyuan/Music/胡夏 - 刀塔传奇.flac',type:'file'},
  {name:'同桌的你',artist:'胡夏',url:'file:///Users/hujiyuan/Music/胡夏 - 同桌的你.flac',type:'file'},
  {name:'蜀山剑道',artist:'胡夏',url:'file:///Users/hujiyuan/Music/胡夏 - 蜀山剑道.flac',type:'file'},
  {name:'还魂门',artist:'胡彦斌',url:'file:///Users/hujiyuan/Music/胡彦斌 - 还魂门.flac',type:'file'},
  {name:'多情种',artist:'胡杨林',url:'file:///Users/hujiyuan/Music/胡杨林 - 多情种.mp3',type:'file'},
  {name:'炙热的心',artist:'艾七月',url:'file:///Users/hujiyuan/Music/艾七月 - 炙热的心.flac',type:'file'},
  {name:'东坡',artist:'艾辰',url:'file:///Users/hujiyuan/Music/艾辰 - 东坡.flac',type:'file'},
  {name:'桃花凉',artist:'艾辰',url:'file:///Users/hujiyuan/Music/艾辰 - 桃花凉.flac',type:'file'},
  {name:'落（我拈来一缕春风）',artist:'艾辰',url:'file:///Users/hujiyuan/Music/艾辰 - 落（我拈来一缕春风）.flac',type:'file'},
  {name:'君不见 (剧情版)',artist:'艾辰 _ 璟年 _ 屿汐学长 _ 麓七',url:'file:///Users/hujiyuan/Music/艾辰 _ 璟年 _ 屿汐学长 _ 麓七 - 君不见 (剧情版).flac',type:'file'},
  {name:'君不见',artist:'艾辰 _ 璟年 _ 屿汐学长 _ 麓七',url:'file:///Users/hujiyuan/Music/艾辰 _ 璟年 _ 屿汐学长 _ 麓七 - 君不见.flac',type:'file'},
  {name:'盗将行',artist:'花粥 _ 马雨阳',url:'file:///Users/hujiyuan/Music/花粥 _ 马雨阳 - 盗将行.flac',type:'file'},
  {name:'REMIX RUMBLE (Steve Aoki Remix)',artist:'英雄联盟',url:'file:///Users/hujiyuan/Music/英雄联盟 - REMIX RUMBLE (Steve Aoki Remix).flac',type:'file'},
  {name:'涅槃 (Phoenix)',artist:'英雄联盟',url:'file:///Users/hujiyuan/Music/英雄联盟 - 涅槃 (Phoenix).flac',type:'file'},
  {name:'Legends Never Die 传奇永不熄',artist:'英雄联盟 _ Against the Current',url:'file:///Users/hujiyuan/Music/英雄联盟 _ Against the Current - Legends Never Die 传奇永不熄.flac',type:'file'},
  {name:'归去来兮',artist:'草帽酱',url:'file:///Users/hujiyuan/Music/草帽酱 - 归去来兮.mp3',type:'file'},
  {name:'遗失的心跳(1)',artist:'萧亚轩',url:'file:///Users/hujiyuan/Music/萧亚轩 - 遗失的心跳(1).flac',type:'file'},
  {name:'遗失的心跳',artist:'萧亚轩',url:'file:///Users/hujiyuan/Music/萧亚轩 - 遗失的心跳.flac',type:'file'},
  {name:'一剑天涯',artist:'萧忆情Alex',url:'file:///Users/hujiyuan/Music/萧忆情Alex - 一剑天涯.mp3',type:'file'},
  {name:'如寄',artist:'萧忆情Alex',url:'file:///Users/hujiyuan/Music/萧忆情Alex - 如寄.flac',type:'file'},
  {name:'无忌',artist:'萧忆情Alex',url:'file:///Users/hujiyuan/Music/萧忆情Alex - 无忌.mp3',type:'file'},
  {name:'思如雪',artist:'董真',url:'file:///Users/hujiyuan/Music/董真 - 思如雪.flac',type:'file'},
  {name:'枕上书',artist:'董真',url:'file:///Users/hujiyuan/Music/董真 - 枕上书.flac',type:'file'},
  {name:'Deadman',artist:'蔡徐坤',url:'file:///Users/hujiyuan/Music/蔡徐坤 - Deadman.flac',type:'file'},
  {name:'石楠小札',artist:'蔡翊昇',url:'file:///Users/hujiyuan/Music/蔡翊昇 - 石楠小札.flac',type:'file'},
  {name:'花间辞',artist:'蔡翊昇 _ 流浪的蛙蛙',url:'file:///Users/hujiyuan/Music/蔡翊昇 _ 流浪的蛙蛙 - 花间辞.mp3',type:'file'},
  {name:'逐浪飞花',artist:'蔡翊昇 _ 流浪的蛙蛙',url:'file:///Users/hujiyuan/Music/蔡翊昇 _ 流浪的蛙蛙 - 逐浪飞花.flac',type:'file'},
  {name:'一世长安',artist:'蔡翊昇 _ 许多葵',url:'file:///Users/hujiyuan/Music/蔡翊昇 _ 许多葵 - 一世长安.flac',type:'file'},
  {name:'未央夜',artist:'袁野',url:'file:///Users/hujiyuan/Music/袁野 - 未央夜.flac',type:'file'},
  {name:'一念山河',artist:'西瓜JUN',url:'file:///Users/hujiyuan/Music/西瓜JUN - 一念山河.flac',type:'file'},
  {name:'寒山客',artist:'西瓜JUN',url:'file:///Users/hujiyuan/Music/西瓜JUN - 寒山客.flac',type:'file'},
  {name:'状元叹',artist:'西瓜JUN',url:'file:///Users/hujiyuan/Music/西瓜JUN - 状元叹.flac',type:'file'},
  {name:'长生诀',artist:'西瓜JUN',url:'file:///Users/hujiyuan/Music/西瓜JUN - 长生诀.mp3',type:'file'},
  {name:'落子无悔',artist:'许八斗 _ 霄磊',url:'file:///Users/hujiyuan/Music/许八斗 _ 霄磊 - 落子无悔.flac',type:'file'},
  {name:'惊鸿一面',artist:'许嵩 _ 黄龄',url:'file:///Users/hujiyuan/Music/许嵩 _ 黄龄 - 惊鸿一面.flac',type:'file'},
  {name:'桃花三千',artist:'谗讥 _ 青阳',url:'file:///Users/hujiyuan/Music/谗讥 _ 青阳 - 桃花三千.flac',type:'file'},
  {name:'云月辞',artist:'赖美云后援会 _ 陆66',url:'file:///Users/hujiyuan/Music/赖美云后援会 _ 陆66 - 云月辞.flac',type:'file'},
  {name:'有人',artist:'赵钶',url:'file:///Users/hujiyuan/Music/赵钶 - 有人.flac',type:'file'},
  {name:'红尘轻剑',artist:'轩寞sirius',url:'file:///Users/hujiyuan/Music/轩寞sirius - 红尘轻剑.mp3',type:'file'},
  {name:'东风志',artist:'辰小弦 _ 双笙 (陈元汐)',url:'file:///Users/hujiyuan/Music/辰小弦 _ 双笙 (陈元汐) - 东风志.mp3',type:'file'},
  {name:'狐言',artist:'辰小弦 _ 双笙 (陈元汐)',url:'file:///Users/hujiyuan/Music/辰小弦 _ 双笙 (陈元汐) - 狐言.mp3',type:'file'},
  {name:'琵琶行',artist:'郑潇',url:'file:///Users/hujiyuan/Music/郑潇 - 琵琶行.flac',type:'file'},
  {name:'天空之城',artist:'郭宴',url:'file:///Users/hujiyuan/Music/郭宴 - 天空之城.flac',type:'file'},
  {name:'风中的花瓣',artist:'醉梦千城',url:'file:///Users/hujiyuan/Music/醉梦千城 - 风中的花瓣.flac',type:'file'},
  {name:'渐行远 (FullSize)',artist:'醉雪',url:'file:///Users/hujiyuan/Music/醉雪 - 渐行远 (FullSize).flac',type:'file'},
  {name:'心爱',artist:'金学峰',url:'file:///Users/hujiyuan/Music/金学峰 - 心爱.flac',type:'file'},
  {name:'思美人兮',artist:'金玟岐',url:'file:///Users/hujiyuan/Music/金玟岐 - 思美人兮.flac',type:'file'},
  {name:'三国醉',artist:'金莎',url:'file:///Users/hujiyuan/Music/金莎 - 三国醉.flac',type:'file'},
  {name:'流光记',artist:'银临',url:'file:///Users/hujiyuan/Music/银临 - 流光记.flac',type:'file'},
  {name:'腐草为萤',artist:'银临',url:'file:///Users/hujiyuan/Music/银临 - 腐草为萤.flac',type:'file'},
  {name:'牵丝戏',artist:'银临 _ Aki阿杰',url:'file:///Users/hujiyuan/Music/银临 _ Aki阿杰 - 牵丝戏.flac',type:'file'},
  {name:'是风动',artist:'银临 _ 河图',url:'file:///Users/hujiyuan/Music/银临 _ 河图 - 是风动.flac',type:'file'},
  {name:'芳华旧',artist:'银临 _ 蔡翊昇',url:'file:///Users/hujiyuan/Music/银临 _ 蔡翊昇 - 芳华旧.mp3',type:'file'},
  {name:'湘桥月',artist:'银临 _ 鸦青',url:'file:///Users/hujiyuan/Music/银临 _ 鸦青 - 湘桥月.mp3',type:'file'},
  {name:'一念乾坤',artist:'阿睿凌霓剑裳',url:'file:///Users/hujiyuan/Music/阿睿凌霓剑裳 - 一念乾坤.mp3',type:'file'},
  {name:'崛起',artist:'陈冰',url:'file:///Users/hujiyuan/Music/陈冰 - 崛起.flac',type:'file'},
  {name:'老男孩 (Live)',artist:'陈冰',url:'file:///Users/hujiyuan/Music/陈冰 - 老男孩 (Live).flac',type:'file'},
  {name:'战无定法',artist:'陈柯宇',url:'file:///Users/hujiyuan/Music/陈柯宇 - 战无定法.flac',type:'file'},
  {name:'之子于归 (独唱版)',artist:'霍尊',url:'file:///Users/hujiyuan/Music/霍尊 - 之子于归 (独唱版).flac',type:'file'},
  {name:'卷珠帘',artist:'霍尊',url:'file:///Users/hujiyuan/Music/霍尊 - 卷珠帘.flac',type:'file'},
  {name:'天行九歌',artist:'霍尊',url:'file:///Users/hujiyuan/Music/霍尊 - 天行九歌.flac',type:'file'},
  {name:'离人泪',artist:'霍尊',url:'file:///Users/hujiyuan/Music/霍尊 - 离人泪.flac',type:'file'},
  {name:'新贵妃醉酒 (Live)',artist:'霍尊 _ 杨树林',url:'file:///Users/hujiyuan/Music/霍尊 _ 杨树林 - 新贵妃醉酒 (Live).flac',type:'file'},
  {name:'冬日',artist:'鞠婧祎',url:'file:///Users/hujiyuan/Music/鞠婧祎 - 冬日.flac',type:'file'},
  {name:'天长',artist:'鞠婧祎',url:'file:///Users/hujiyuan/Music/鞠婧祎 - 天长.flac',type:'file'},
  {name:'红昭愿 (Live)',artist:'鞠婧祎',url:'file:///Users/hujiyuan/Music/鞠婧祎 - 红昭愿 (Live).flac',type:'file'},
  {name:'醉飞霜',artist:'鞠婧祎',url:'file:///Users/hujiyuan/Music/鞠婧祎 - 醉飞霜.flac',type:'file'},
  {name:'小尖尖',artist:'韩红 _ 薛之谦',url:'file:///Users/hujiyuan/Music/韩红 _ 薛之谦 - 小尖尖.flac',type:'file'},
  {name:'挑灯看剑',artist:'音阙诗听',url:'file:///Users/hujiyuan/Music/音阙诗听 - 挑灯看剑.flac',type:'file'},
  {name:'主宰',artist:'音频怪物',url:'file:///Users/hujiyuan/Music/音频怪物 - 主宰.mp3',type:'file'},
  {name:'拂世之剑',artist:'音频怪物',url:'file:///Users/hujiyuan/Music/音频怪物 - 拂世之剑.flac',type:'file'},
  {name:'浮生未歇',artist:'音频怪物',url:'file:///Users/hujiyuan/Music/音频怪物 - 浮生未歇.mp3',type:'file'},
  {name:'帝皇再临',artist:'颜寰青',url:'file:///Users/hujiyuan/Music/颜寰青 - 帝皇再临.mp3',type:'file'},
  {name:'恋人心',artist:'魏新雨',url:'file:///Users/hujiyuan/Music/魏新雨 - 恋人心.flac',type:'file'},
  {name:'忆北海道',artist:'鹭起Herons',url:'file:///Users/hujiyuan/Music/鹭起Herons - 忆北海道.flac',type:'file'},
  {name:'九万字 (念白版)',artist:'黄诗扶',url:'file:///Users/hujiyuan/Music/黄诗扶 - 九万字 (念白版).flac',type:'file'},
  {name:'九万字',artist:'黄诗扶',url:'file:///Users/hujiyuan/Music/黄诗扶 - 九万字.flac',type:'file'},
  {name:'牵丝戏 (梦幻西游盘丝洞门派曲)',artist:'黄龄',url:'file:///Users/hujiyuan/Music/黄龄 - 牵丝戏 (梦幻西游盘丝洞门派曲).flac',type:'file'},
  {name:'下山',artist:'龚琳娜',url:'file:///Users/hujiyuan/Music/龚琳娜 - 下山.flac',type:'file'}
];
window.RADIO_STATIONS = [
  { name: 'SomaFM - Groove Salad', artist: 'Ambient/Downtempo', url: 'https://ice1.somafm.com/groovesalad-128-mp3', type: 'stream' },
  { name: 'SomaFM - Drone Zone', artist: 'Ambient', url: 'https://ice1.somafm.com/dronezone-128-mp3', type: 'stream' },
  { name: 'SomaFM - Lush', artist: 'Electronic', url: 'https://ice1.somafm.com/lush-128-mp3', type: 'stream' },
  { name: 'SomaFM - Secret Agent', artist: 'Lounge/Spy', url: 'https://ice1.somafm.com/secretagent-128-mp3', type: 'stream' },
  { name: 'SomaFM - Space Station', artist: 'Space/Ambient', url: 'https://ice1.somafm.com/spacestation-128-mp3', type: 'stream' },
  { name: 'SomaFM - Beat Blender', artist: 'Electronic/Dance', url: 'https://ice1.somafm.com/beatblender-128-mp3', type: 'stream' },
  { name: 'SomaFM - Indie Pop Rocks', artist: 'Indie Pop', url: 'https://ice1.somafm.com/indiepop-128-mp3', type: 'stream' },
  { name: 'SomaFM - The Trip', artist: 'Progressive House', url: 'https://ice1.somafm.com/thetrip-128-mp3', type: 'stream' },
  { name: 'SomaFM - Vaporwaves', artist: 'Vaporwave', url: 'https://ice1.somafm.com/vaporwaves-128-mp3', type: 'stream' },
  { name: 'Radio Paradise - Main', artist: 'Eclectic Rock', url: 'https://stream.radioparadise.com/mp3-192', type: 'stream' },
  { name: 'Radio Paradise - Mellow', artist: 'Mellow Mix', url: 'https://stream.radioparadise.com/mellow-192', type: 'stream' },
  { name: '1FM - LoFi Hip Hop', artist: 'Lo-Fi', url: 'https://streams.ilovemusic.de/iloveradio17.mp3', type: 'stream' },
  { name: 'NTS Radio', artist: 'Eclectic', url: 'https://stream-relay-geo.ntslive.net/stream', type: 'stream' },
];
